### ISSUE TITLE
Spelunker only works while underwater.

### ISSUE THREAD

**Issue by Nelaroth** [Lex305/Spelunker#5]
When I have the spelunker effect, I am only able to see ores highlighted when I am in water.
 ![image](https://user-images.githubusercontent.com/59890096/162688581-13d7ac18-c966-40db-9e8d-75ae10cb2064.png)
I have added the ores from MythicMetals, BetterEnd, and BetterNether to the list of ores to be highlighted, but otherwise I changed nothing since I last tested the mod yesterday.
![image](https://user-images.githubusercontent.com/59890096/162688935-ce33b800-aaf1-4f9d-84c3-3580b6caf501.png)
![image](https://user-images.githubusercontent.com/59890096/162688979-801e15eb-1384-42fd-b090-e9720b5751a0.png)

**Comment by Nelaroth** [comment]
Okay, so it seems to work if it's not an air block.
![image](https://user-images.githubusercontent.com/59890096/162691114-3c18f82a-4c08-4bd0-b45f-92fced76bca2.png)

3rd person view of the above picture
![image](https://user-images.githubusercontent.com/59890096/162691272-09e395b2-febc-4eb9-88c7-fbe4392e096b.png)


I think it is somehow reading air blocks as an ore.

**Comment by Leximon** [comment]
thx for your report!
Can you attach the config file and if possible, send me the list of mods you are using?

**Comment by Nelaroth** [comment]
Here's the config file
[Spelunker Config.txt](https://github.com/Leximon/Spelunker/files/8466602/Spelunker.Config.txt)
I'll try to attach the modlist in a second. I'll be honest, I'm new to this, and don't know if there is an easy way to find the list.

**Comment by Leximon** [comment]
I think I have an explanation for this.
As soon you add a block id that doesn't exist in the config the mod will recognize it as an air block
make sure you haven't typed any id wrong that should fix this issue

**Comment by Leximon** [comment]
I'll make an update for this mod so you get a warning instead
but because this bug is not that critical this won't happen soon

**Comment by Nelaroth** [comment]
Thank you for looking into it! I did have two ores misspelt. After fixing the typos, air blocks aren't being read as ores anymore. Thank you once again for your time.

**Comment by pawbap** [comment]
I don't wanna open a new issue, because this looks similar to my problem I'm having right now. For some reason, the mod isn't recognising the block IDs I'm trying to add, and I've tried all sorts of combinations but nothing seems to work. I'm trying to add Sulfur and Potassium ores from the [Sulfur And Potassium - More Gunpowder](https://www.curseforge.com/minecraft/mc-mods/sulfur-and-potassium-make-more-gunpowder), but this is what happens instead...
![2022-04-18_23 54 32](https://user-images.githubusercontent.com/102625726/163883934-85e6ade6-2658-44d8-bc3d-e482dd8222fe.png)
![2022-04-18_23 55 15](https://user-images.githubusercontent.com/102625726/163883938-dc39ac3e-df5f-41c2-b108-d91b0da47575.png)
![2022-04-18_23 55 17](https://user-images.githubusercontent.com/102625726/163883939-fd01c390-74fd-49ed-a948-57127211621e.png)

The IDs SHOULD be matching, I'm 99.9% sure.

![image](https://user-images.githubusercontent.com/102625726/163884801-13333d59-8ee3-4b1a-af37-a19c05dd6f8f.png)
![Code_2022-04-19_00-03-54](https://user-images.githubusercontent.com/102625726/163884877-55d9ac20-9a7e-4171-b324-edfd2e55d03f.png)
![Code_2022-04-19_00-00-58](https://user-images.githubusercontent.com/102625726/163884887-6a076687-4001-40b8-8285-ac2301e26496.png)

What am I missing?

**Comment by Leximon** [comment]
It might be the problem that the spelunker mod loads before the sulfur and potassium mod loads
that would be a good explanation for this issue
I will try to fix it soon

**Comment by pawbap** [comment]
Really? I didn't know mod load order could be an issue in MC modding.

For the sake of experimentation, I tried making Spelunker work with [Basic Nether Ores](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores) (namespace: "bno"), which did work as expected. Then I tried again with [Universal Ores](https://www.curseforge.com/minecraft/mc-mods/universal-ores-fabric) (namespace: "universal_ores") and, lo and behold, the issue occurs... Looking back at OP's problem, the namespaces for all their mods started with a letter before S in the alphabet. Interesting!

**Comment by TofuToons** [comment]
Just want to chime in and say that I am also having the same issue of any block that is loaded after the spelunker mod does not work in the config file. Notable mods:

-Unearthed (Adds vanilla ore variants for all the stones that the mod adds)
-Valleycraft
